first/first/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'', include('firstapp.urls'))
]

first/firstapp/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url
from .views import index, form_name_view, createtopic, register

app_name = 'firstapp'

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^we$', form_name_view, name='demoform'),
    url(r'^create$', createtopic, name='create'),

    url(r'^register/$', register, name='userregistration'),
    # url(r'login/$', user_login, name='login')
]

first/firstapp/models.py
from django.db import models
from django.contrib.auth.models import User


class Userprofile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)

    portfolio = models.URLField(blank=True)
    picture = models.ImageField(upload_to='profile_pics',blank=True)

    def __str__(self):
        return self.user.username


class Topic(models.Model):
    top_name = models.CharField(max_length=250, unique=True)

    def __str__(self):
        return self.top_name


class Webpage(models.Model):
    category = models.ForeignKey(Topic, on_delete=models.CASCADE)
    name = models.CharField(max_length=264, unique=True)
    url = models.URLField()

    def __str__(self):
        return self.name


class AccessRecord(models.Model):
    name = models.ForeignKey(Webpage, on_delete=models.CASCADE)
    date = models.DateField()

    def __str__(self):
        return str(self.date)

first/firstapp/forms.py
from django import forms
from .models import Topic, Userprofile
from django.contrib.auth.models import User


# class Userprofileform(forms.ModelForm):
#     portfolio = forms.URLField(required=False)
#     picture = forms.ImageField(required=False)
#
#     class Meta:
#         model = Userprofile
#         exclude = ('user',)

class Userform(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password')


class UserProfileInfo(forms.ModelForm):
    class Meta:
        model = Userprofile
        fields = ('portfolio', 'picture')


class AddTopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = "__all__"


class Webform(forms.Form):
    name = forms.CharField()
    email = forms.EmailField()
    text = forms.CharField(widget=forms.Textarea)
    password = forms.CharField(widget=forms.PasswordInput)
    reenter_password = forms.CharField(widget=forms.PasswordInput)

    def clean(self):
        all_clean_data = super().clean()
        password = all_clean_data['password']
        rpassword = all_clean_data['reenter_password']

        if password != rpassword:
            raise forms.ValidationError('password doesnt match')
        return all_clean_data

first/firstapp/views.py
from django.shortcuts import render, redirect
from django import forms
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout

from firstapp.models import Webpage, AccessRecord, Topic
from .forms import Webform, AddTopicForm, Userform, UserProfileInfo


def index(request):
    webpage_list = AccessRecord.objects.order_by('date')
    date_dict = {'access_record': webpage_list}
    return render(request, 'firstapp/index.html', context=date_dict)


def form_name_view(request):
    form = Webform()

    if request.method == 'POST':
        form = Webform(request.POST)
        if form.is_valid():
            print(form.cleaned_data['name'])
            print(form.cleaned_data['email'])
            print(form.cleaned_data['text'])

    return render(request, 'firstapp/demoform.html', {'form': form})


def createtopic(request):
    form = AddTopicForm()

    if request.method == 'POST':
        form = AddTopicForm(request.POST)

        if form.is_valid:
            form.save(commit=True)
            return index(request)
        else:
            print("error")
    return render(request, 'firstapp/newform.html', {'form': form})


def register(request):
    registered = False
    if request.method == 'POST':
        user_form = Userform(data=request.POST)
        profile_form = UserProfileInfo(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pics' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']
            profile.save()
            registered = True

        else:
            print(user_form.errors)


    else:
        user_form = Userform()
        profile_form = UserProfileInfo()
    return render(request, 'firstapp/registeration.html', {'user_form': user_form,
                                                           'profile_form': profile_form,
                                                           'registered': registered
                                                           })

#
# @login_required
# def user_logout(request):
#     logout(request)
#     return HttpResponse('User Logout Successfully')
#
#
# def user_login(request):
#     if request.method == 'POST':
#         username = request.POST.get('username')
#         password = request.POST.get('password')
#
#         user = authenticate(username=username, password=password)
#         print(user)
#         if user:
#             if user.is_active:
#                 login(request, user)
#                 return HttpResponseRedirect(reverse('index'))
#             else:
#                 return HttpResponse('Accounts Not Active')
#         else:
#             return HttpResponse('invaliid login details')
#     else:
#         return render(request, 'firstapp/login.html', {})

first/templates/firstapp/demoform.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form method="post">
    {{ form.as_p }}
    {% csrf_token %}
    <input type="submit" value="submit">
</form>
</body>
</html>

first/templates/firstapp/index.html
{% load staticfiles %}
<html>
<head>
    <title>Hello this is djangoo</title>
    <link rel="stylesheet" href="{% static 'firstapp/css/style.css' %}">
</head>
<div>
    <a href="{% url 'firstapp:create' %}">
        <button>Create</button>
    </a>
    {% if access_record %}
        <table>
            <thead>
            <th>Name</th>
            <th>Custom name</th>
            <th>date</th>
            <th>Year</th>
            <th>Month</th>
            <th>Day</th>
            </thead>
            {% for acc in access_record %}
                <tr>
                    <td>{{ acc.name }}</td>
                    <td>{{ acc.name|lower|cut:'y' }}</td>
                    <td>{{ acc.date|date:'d-m-Y' }}</td>
                    <td>{{ acc.date|date:'Y'|add:'100' }}</td>
                    <td>{{ acc.date|date:'M' }}</td>
                    <td>{{ acc.date|date:'D' }}</td>
                </tr>
            {% endfor %}
        </table>
    {% else %}
        <p>No access Records Found</p>
    {% endif %}
</div>
</html>

first/templates/firstapp/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>User login</title>
</head>
<body>
<form method="post" action="{% url 'firstapp:login' %}">
    {% csrf_token %}
    <input type="text" name="username" placeholder="Enter user-Name">
    <input type="password" name="password" placeholder="Enter password">
    <input type="submit" value="login">
</form>
</body>
</html>

first/templates/firstapp/newform.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>New form</title>
</head>
<body>
<form method="post">
    {{ form.as_p }}
    {% csrf_token %}
    <input type="submit" value="submit">
</form>
</body>
</html>

first/templates/firstapp/registeration.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% if registered %}
    <h1>thank you for registering</h1>
{% else %}
    <h1>Register here</h1>
    <form method="post" action="" enctype="multipart/form-data">
    {% csrf_token %}
    {{ user_form.as_p }}
    {{ profile_form.as_p }}
    <input type="submit" value="submit">
    </form>
{% endif %}
</body>
</html>